### ISSUE TITLE
Data ophalen en svelte kit project setup zetten

### ISSUE THREAD

**Issue by Jesse-L3** [J3SS3HVA/your-tribe-for-life-profile-card#2]
Omdat de content dynamisch is moeten we alles van de directus api halen. niet alleen dat, ook moet mijn project enviroment ook helemaal complete zijn voordat ik begin met stylen.

Met het ontwerp wat ik heb gemaakt kan ik zien welke content ik uit de directus api moet ophalen + waar ik de data op moet filteren sinds ik alleen mijn person id nodig heb

**Comment by 1234abd** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
